package enpit.sample.adf1221.restsandbox.model.query;

import enpit.sample.adf1221.restsandbox.model.query.common.EmployeesView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 14 19:14:54 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }
    
    public String doSomethingInVO(String param1){
        System.out.println("do Smth in VO: " + param1);
        return "nothing done in VO: " + param1;
    }

    /**
     * Returns the variable value for EmailBindVar.
     * @return variable value for EmailBindVar
     */
    public String getEmailBindVar() {
        return (String) ensureVariableManager().getVariableValue("EmailBindVar");
    }

    /**
     * Sets <code>value</code> for variable EmailBindVar.
     * @param value value to bind as EmailBindVar
     */
    public void setEmailBindVar(String value) {
        ensureVariableManager().setVariableValue("EmailBindVar", value);
    }
}

