package enpit.sample.adf1221.restsandbox.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 14 19:14:23 CET 2016
// ---------------------------------------------------------------------
public interface HRAppModule extends ApplicationModule {
    String doSomething(String param1);
}

