package enpit.sample.adf1221.restsandbox.model.query.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 15 00:03:47 CET 2016
// ---------------------------------------------------------------------
public interface EmployeesViewRow extends Row {
    String doSomethingInVORow(String param1);
}

