package enpit.sample.adf1221.restsandbox.model.query.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 14 19:16:11 CET 2016
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    String doSomethingInVO(String param1);
}

